### PR TITLE
Parcoords: ellipsize long labels; show full text in tooltip

### PR DESCRIPTION
**Pull request by kernc**
Ellipsizes labels that are too long to prevent overlapping. But always show full label text in mouse hover tooltip.

### Before
screenshot - 05182017 - 07 49 37 pm

### After
screenshot - 05182017 - 07 47 22 pm

### CODE REVIEW

**Comment by kernc** [comment]
@monfera Could you have a quick look at this? It's only five lines or so.

**Comment by monfera** [comment]
@kernc thanks for the PR, I see it's been around for quite some time. I'm on another task now, will check back with you ASAP.

**Comment by monfera** [comment]
@kernc your PR didn't register with us b/c it's a PR toward your own repo rather than the upstream (ie. it doesn't show up here: https://github.com/plotly/plotly.js/pulls) - there are some key issues, please issue the PR toward the `plotly` org as it's a better place for comments

**Comment by kernc** [comment]
I was just following [your PR guidelines](https://github.com/plotly/plotly.js/blob/master/.github/PULL_REQUEST_TEMPLATE.md) which state:
> Developers are strongly encouraged to first make a PR to their own plotly.js fork and ask one of the maintainers to review the modifications there. Once the pull request is deemed satisfactory, ...

Will open a PR there, thanks.

**Comment by monfera** [comment]
Indeed, you're right! I saw the PR is dated May 18 and saw no conversation.

**Comment by kernc** [comment]
Some conversation took place in https://github.com/plotly/plotly.js/issues/1703. 😃 

Continued in https://github.com/plotly/plotly.js/pull/1857.

**Pull request closed without merging**
